import type { Metadata } from "next";
import "reflect-metadata"
import { Provider } from "@/components/ui/provider"
import Nav from "./components/Nav";
import { SessionProvider } from "next-auth/react"
import { AuthProvider } from "@/app/context/Auth";

export const metadata: Metadata = {
  title: "Favorite Cities",
  description: "Generated by CN",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <SessionProvider>
            <AuthProvider >
              <Nav />
              {children}
            </AuthProvider>
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}
